---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: service-accounts-credentials-secret
  namespace: rh-platform-experien-tenant
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: insights-appsre-vault
    kind: ClusterSecretStore
  target:
    name: service-accounts-credentials-secret
    creationPolicy: Owner
  data:
    - secretKey: e2e-user
      remoteRef:
        key: creds/konflux/service-accounts
        property: username
    - secretKey: e2e-password
      remoteRef:
        key: creds/konflux/service-accounts
        property: password
    - secretKey: e2e-hcc-env-url
      remoteRef:
        key: creds/konflux/service-accounts
        property: e2e-hcc-env-url
    - secretKey: e2e-stage-actual-hostname
      remoteRef:
        key: creds/konflux/service-accounts
        property: e2e-stage-actual-hostname
