# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json

apiVersion: v1
kind: Template
metadata:
  name: service-accounts
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: service-accounts
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/service-accounts
      title: "Service accounts"
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/service-accounts
      serviceTiles:
      - id: iam
        section: iam
        group: iam
        href: /iam/service-accounts
        title: Service accounts
        description: ''
        icon: PlaceholderIcon
      searchEntries:
      - id: service-accounts
        title: Service accounts
        href: /iam/service-accounts
        description: ''

      bundleSegments:
        - segmentId: service-accounts-iam
          bundleId: iam
          position: 2000
          navItems:
          - id: service-accounts
            title: Service Accounts
            href: /iam/service-accounts
            permissions:
            - method: featureFlag
              args:
              - platform.iam.service-accounts
              - true
      module:
        manifestLocation: "/apps/service-accounts/fed-mods.json"
        modules:
        - id: service-accounts
          module: "./RootApp"
          routes:
          - pathname: "/iam/service-accounts"
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/rh-platform-experien-tenant/service-accounts
