apiVersion: v1
kind: Template
metadata:
  name: service-accounts
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: service-accounts
    spec:
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/service-accounts
      title: "Service accounts"
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/service-accounts
      navItems:
      - appId: serviceAccounts
        title: "Service accounts"
        href: /iam/service-accounts
      module:
        manifestLocation: "/apps/service-accounts/fed-mods.json"
        modules:
        - id: "serviceAccounts"
          module: "./RootApp"
          routes:
          - pathname: /iam/service-accounts
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/service-accounts
